"""empty message

Revision ID: 188502571ee9
Revises: None
Create Date: 2017-09-27 13:10:30.932000

"""

# revision identifiers, used by Alembic.
revision = '188502571ee9'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_bank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nm_bank', sa.String(length=15), nullable=False),
    sa.Column('norek', sa.String(length=35), nullable=False),
    sa.Column('img_bank', sa.String(length=150), nullable=False),
    sa.Column('createDate', sa.TIMESTAMP(), nullable=True),
    sa.Column('updateDate', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nm_cat', sa.String(length=50), nullable=False),
    sa.Column('img_cat', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_nm', sa.String(length=200), nullable=False),
    sa.Column('product_price', sa.Integer(), nullable=False),
    sa.Column('product_desc', sa.String(length=700), nullable=True),
    sa.Column('product_weight', sa.Integer(), nullable=True),
    sa.Column('product_color', sa.String(length=10), nullable=True),
    sa.Column('product_img', sa.String(length=100), nullable=False),
    sa.Column('createDate', sa.TIMESTAMP(), nullable=True),
    sa.Column('updateDate', sa.TIMESTAMP(), nullable=True),
    sa.Column('isDelete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=100), nullable=False),
    sa.Column('user_pw', sa.String(length=50), nullable=False),
    sa.Column('user_nm', sa.String(length=100), nullable=False),
    sa.Column('user_jk', sa.String(length=10), nullable=True),
    sa.Column('user_notelp', sa.String(length=14), nullable=False),
    sa.Column('user_birthDate', sa.DATE(), nullable=True),
    sa.Column('createDate', sa.TIMESTAMP(), nullable=True),
    sa.Column('updateDate', sa.TIMESTAMP(), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.Column('isDelete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nm_penerima', sa.String(length=30), nullable=False),
    sa.Column('alamat', sa.String(length=150), nullable=False),
    sa.Column('province', sa.String(length=20), nullable=False),
    sa.Column('notelp_penerima', sa.String(length=14), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('createDate', sa.TIMESTAMP(), nullable=True),
    sa.Column('updateDate', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['t_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('no_invoice', sa.String(length=15), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('status_order', sa.Boolean(), nullable=True),
    sa.Column('payment_to_bank', sa.Integer(), nullable=True),
    sa.Column('shipping', sa.Integer(), nullable=True),
    sa.Column('id_address', sa.Integer(), nullable=True),
    sa.Column('createDate', sa.TIMESTAMP(), nullable=True),
    sa.Column('updateDate', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['id_address'], ['t_address.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['t_user.id'], ),
    sa.ForeignKeyConstraint(['payment_to_bank'], ['t_bank.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_order', sa.Integer(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_product', sa.Integer(), nullable=True),
    sa.Column('jml_product', sa.Integer(), nullable=False),
    sa.Column('cart_status', sa.Boolean(), nullable=True),
    sa.Column('createDate', sa.TIMESTAMP(), nullable=True),
    sa.Column('updateDate', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['id_order'], ['t_order.id'], ),
    sa.ForeignKeyConstraint(['id_product'], ['t_product.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['t_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_cart')
    op.drop_table('t_order')
    op.drop_table('t_address')
    op.drop_table('t_user')
    op.drop_table('t_product')
    op.drop_table('t_category')
    op.drop_table('t_bank')
    ### end Alembic commands ###
