"""empty message

Revision ID: 2793b51df414
Revises: 378ed7934652
Create Date: 2017-11-18 01:42:55.257000

"""

# revision identifiers, used by Alembic.
revision = '2793b51df414'
down_revision = '378ed7934652'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_user', sa.Column('token_firebase', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_user', 'token_firebase')
    ### end Alembic commands ###
