"""empty message

Revision ID: 3bfcd49c1100
Revises: 458cd9786aca
Create Date: 2017-11-27 22:04:37.071000

"""

# revision identifiers, used by Alembic.
revision = '3bfcd49c1100'
down_revision = '458cd9786aca'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_category', sa.Column('createDate', sa.TIMESTAMP(), nullable=True))
    op.add_column('t_category', sa.Column('isDelete', sa.Boolean(), nullable=True))
    op.add_column('t_category', sa.Column('updateDate', sa.TIMESTAMP(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_category', 'updateDate')
    op.drop_column('t_category', 'isDelete')
    op.drop_column('t_category', 'createDate')
    ### end Alembic commands ###
