"""empty message

Revision ID: 458cd9786aca
Revises: None
Create Date: 2017-11-26 19:00:21.811000

"""

# revision identifiers, used by Alembic.
revision = '458cd9786aca'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_product', sa.Column('product_stock', sa.String(length=15), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_product', 'product_stock')
    ### end Alembic commands ###
