"""empty message

Revision ID: 54a02e39be35
Revises: 2793b51df414
Create Date: 2017-11-25 01:27:49.783000

"""

# revision identifiers, used by Alembic.
revision = '54a02e39be35'
down_revision = '2793b51df414'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_product', sa.Column('product_category', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 't_product', 't_category', ['product_category'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 't_product', type_='foreignkey')
    op.drop_column('t_product', 'product_category')
    ### end Alembic commands ###
